name: DannyShop
main: me.danny.shop.DannyShop
version: "${git_commit}"
author: Danny
description: Danny's shop plugin for Spigot
api-version: 1.19
softdepend:
  - Essentials
  - Vault
  - InputAPI
website: https://github.com/dashaw92/DannyShop
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.0
  - org.spongepowered:configurate-yaml:4.1.2
commands:
  dannyshop:
    aliases: [ "shop", "danshop", "dshop", "dannyssupercoolshopplugin", "anexcessivelylongaliasfortheshop" ]
    description: DannyShop main command
    usage: /<command> args
  # Test command (functionality varies)
  dannytest:
    description: Lol
    usage: /<command>