name: DannyShop
main: me.danny.shop.DannyShop
version: "${git_commit}"
author: Danny
description: Danny's shop plugin for Spigot
api-version: "${spigot_api}"
softdepend:
  - Vault #
  - WorldGuard # Sell wand
  - GriefPrevention # Sell wand
website: https://github.com/dashaw92/DannyShop
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}
  - org.spongepowered:configurate-yaml:${configurate_version}
commands:
  dannyshop:
    aliases: [ "s", "sh", "shop", "danshop", "dshop", "dannyssupercoolshopplugin", "anexcessivelylongaliasfortheshop" ]
    description: DannyShop main command
    usage: /<command> args
  sell:
    aliases: [ "stonks", "dansell", "makemoney", "bigbusinesstime", "hustle" ]
    description: "Sell command!"
    usage: /<command> <mode> [amount]
permissions:
  dannyshop.*:
    default: op
    children:
      dannyshop.admin: true
      dannyshop.ecolog.logs: true
      dannyshop.ecolog.volume: true
      dannyshop.shop: true
      dannyshop.sell: true
      dannyshop.sellwand: true
  dannyshop.admin:
    default: op
    children:
      dannyshop.ecolog.logs: true
      dannyshop.ecolog.volume: true
      dannyshop.shop: true
      dannyshop.sell: true
      dannyshop.sellwand: true
  dannyshop.shop:
    default: true
    description: Grants access to view the shop only.
  dannyshop.sell:
    default: true
    description: Grants the ability to sell items.
    children:
      dannyshop.shop: true
  dannyshop.sellwand:
    default: true
    description: Grants access to the sell wand.
    children:
      dannyshop.sell: true
      dannyshop.shop: true
  dannyshop.ecolog.*:
    default: op
    description: Grants access to the EcoLog features.
    children:
      dannyshop.ecolog.logs: true
      dannyshop.ecolog.volume: true
  dannyshop.ecolog.logs:
    default: op
    description: Grants access to the sale logs.
  dannyshop.ecolog.volume:
    default: op
    description: Grants access to volume history features.