name: DannyShop
main: me.danny.shop.DannyShop
version: "${git_commit}"
author: Danny
description: Danny's shop plugin for Spigot
api-version: "${spigot_api}"
softdepend:
#  - Essentials
  - Vault
#  - InputAPI
website: https://github.com/dashaw92/DannyShop
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}
  - org.spongepowered:configurate-yaml:${configurate_version}
commands:
  dannyshop:
    aliases: [ "shop", "danshop", "dshop", "dannyssupercoolshopplugin", "anexcessivelylongaliasfortheshop" ]
    description: DannyShop main command
    usage: /<command> args